sudo: required
services:
  - docker

before_install:
  - docker build -t randybui/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true randybui/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-app"
  env: "React-app-env"
  bucket_name: "elasticbeanstalk-us-east-2-326509730982"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secrete_access_key: "$AWS_SECRET_KEY"
